### ISSUE TITLE
failed to install pointgroup_ops

### ISSUE THREAD

**Issue by z-yf17** [sunjiahao1999/SPFormer#9]
Hi! Thanks for your great work.
I've got some trouble when installing pointgroup_ops as follows:

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.1'
running install
/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pointgroup_ops.egg-info/PKG-INFO
writing dependency_links to pointgroup_ops.egg-info/dependency_links.txt
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    setup(
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 155, in run
    self.run_command("egg_info")
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 311, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 738, in write_toplevel_names
    [
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 738, in <listcomp>
    [
  File "/home/zhangyifan/tempconda/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/dist.py", line 1183, in iter_distribution_names
    name = ext.name
AttributeError: 'NoneType' object has no attribute 'name'

How can I fix it? Thank you!

**Comment by qzp2018** [comment]
because you forget to install corresoponding Pytorch 1.10

**Comment by qzp2018** [comment]
because you didn't install the corresponding torch version pytorch 1.10

**Comment by medhanshrath-t** [comment]
Are you using docker? I made it run by running it in the container once it is built, since GPU is not available during docker build

**Comment by YunZhou0321** [comment]
I'm using PyTorch 2.0. I removed the following line from the file SPFormer/spformer/lib/pointgroup_ops/src/bfs_cluster/bfs_cluster.h: #include <THC/THC.h>. After removing it, the installation seemed to succeed, but I haven't run the code yet, so I'm not sure whether it works properly.

![Image](https://github.com/user-attachments/assets/7f945c5f-a454-4dca-9b5b-5874cbb19d4b)
